spring:
    config:
        activate:
            on-profile: local

jwt:
    access-header: Authorization
    refresh-header: Refresh
    secret: localocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocal
    expiration:
        access-token: 1814400000
        refresh-token: 2592000000
    grant-type: Bearer

slack:
    webhook:
        is-enable: false
        url: url
