spring:
    profiles:
        default: ${application-profile}
    application:
        title: Lovebird
        version: 1.0.0
    banner:
        location: classpath:/app-banner.dat
    config:
        import:
            - db-${spring.profiles.default}.yml
            - logging-${spring.profiles.default}.yml
