spring:
    profiles:
        default: ${APPLICATION_PROFILE}
    application:
        title: Lovebird
        version: 1.1.0
    banner:
        location: classpath:/app-banner.dat
    config:
        import:
            - db-${spring.profiles.default}.yml
            - client-${spring.profiles.default}.yml
            - s3-${spring.profiles.default}.yml
            - fcm.yml
            - logging-${spring.profiles.default}.yml
            - monitoring.yml

apple:
    test-code: ${APPLE_TEST_CODE}

aes:
    secret-key: ${AES_SECRET_KEY}
