spring:
    config:
        activate:
            on-profile: prod

jwt:
    access-header: ${ACCESS_HEADER}
    refresh-header: ${REFRESH_HEADER}
    secret: ${PROD_JWT_SECRET}
    expiration:
        access-token: ${JWT_ACCESS_TOKEN_EXPIRATION}
        refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION}
    grant-type: Bearer

slack:
    webhook:
        is-enable: true
        url: ${SLACK_WEBHOOK_URL}
