spring:
    config:
        activate:
            on-profile: dev

jwt:
    access-header: ${ACCESS_HEADER}
    refresh-header: ${REFRESH_HEADER}
    secret: ${DEV_JWT_SECRET}
    expiration:
        access-token: 1814400000
        refresh-token: 2592000000
    grant-type: Bearer

